title: Whimsical Soul Speak
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! Here I share my thoughts on various topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.whimsicalsoulspeak.com" # the base hostname & protocol for your site
#theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  
# Permalinks
permalink: /:year/:month/:day/:title.html